# Generated by Django 2.2.12 on 2020-12-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('docData', models.DateField(blank=True, default=None, null=True)),
                ('sendAuthor', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('dateReg', models.DateField(blank=True, default=None, null=True)),
                ('numberReg', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('dataType', models.CharField(choices=[('ТЗ', 'Территориальная зона'), ('ЗОУИТ', 'Зона с особыми условиями использования территорий')], max_length=8)),
                ('status', models.CharField(choices=[('inwork', 'В работе'), ('closed', 'Завершен'), ('fail', 'Отозван')], max_length=8)),
                ('dateEnd', models.DateField(blank=True, default=None, null=True)),
                ('userCreated', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvdNumber', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('kuvdNumber', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('appealNumber', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('dateCreated', models.DateField(blank=True, default=None, null=True)),
                ('dateReglament', models.DateField(blank=True, default=None, null=True)),
                ('dateClosed', models.DateField(blank=True, default=None, null=True)),
                ('dataType', models.CharField(choices=[('ТЗ', 'Территориальная зона'), ('ЗОУИТ', 'Зона с особыми условиями использования территорий')], max_length=8)),
                ('objectName', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('docName', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('appealResult', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('notification', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('userFinished', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ipd_xml_to_mif.Contractor')),
                ('requestdoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ipd_xml_to_mif.RequestDoc')),
            ],
        ),
    ]
