# Generated by Django 2.2.12 on 2020-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckygardener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestluckygardener',
            name='image',
        ),
        migrations.AddField(
            model_name='contestluckygardener',
            name='image_ns',
            field=models.ImageField(blank=True, null=True, upload_to='luckygarsener'),
        ),
        migrations.AddField(
            model_name='contestluckygardener',
            name='image_ss',
            field=models.ImageField(blank=True, null=True, upload_to='luckygarsener'),
        ),
    ]
