# Generated by Django 2.2.12 on 2020-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckygardener', '0002_auto_20201004_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
