# Generated by Django 2.2.12 on 2020-08-18 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('upks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=1024)),
                ('doc_number', models.CharField(max_length=64)),
                ('doc_date', models.DateField(default=datetime.date.today)),
                ('doc_author', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FilesCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('filepath', models.CharField(default=None, max_length=256)),
                ('urlfile', models.URLField(default=None, max_length=1024)),
                ('datetime_load', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XmlDocEgrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=256)),
                ('filepath', models.CharField(default=None, max_length=256)),
                ('urlfile', models.URLField(default=None, max_length=1024)),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.Docs')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_num', models.CharField(max_length=64)),
                ('cad_num_block', models.CharField(default=None, max_length=64)),
                ('obj_type', models.CharField(default='002001001000', max_length=64)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.CadastrCosts')),
                ('filecost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.FilesCost')),
            ],
        ),
        migrations.AddField(
            model_name='cadastrcosts',
            name='doc_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.Docs'),
        ),
    ]
