# Generated by Django 2.2.12 on 2020-09-12 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('upks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClAssignationBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignationBuildingCode', models.CharField(max_length=12)),
                ('AssignationBuildingName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClAssignationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignationFlatCode', models.CharField(max_length=12)),
                ('AssignationFlatName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClAssignationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignationTypeCode', models.CharField(max_length=12)),
                ('AssignationTypeName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClCadCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unut', models.CharField(max_length=64)),
                ('date_entering', models.DateField(blank=True, default=None, null=True)),
                ('date_approval', models.DateField(blank=True, default=None, null=True)),
                ('date_application', models.DateField(blank=True, default=None, null=True)),
                ('date_valuation', models.DateField(blank=True, default=None, null=True)),
                ('doc_num', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('doc_date', models.DateField(blank=True, default=None, null=True)),
                ('doc_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClCadNumNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClElementConstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClElementConstrCode', models.CharField(max_length=12)),
                ('ClElementConstrName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClExploitationChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_build', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('year_used', models.CharField(blank=True, default=None, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClKeyParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClKeyParamTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClKeyParamCode', models.CharField(max_length=2)),
                ('ClKeyParamName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okato', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('kladr', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('oktmo', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('region', models.IntegerField()),
                ('district_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('district_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('city_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('city_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('locality_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('locality_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('street_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('street_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('home_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('home_number', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('corp_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('corp_number', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('str_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('str_number', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('apart_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('apart_number', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectTypeCode', models.CharField(max_length=10)),
                ('ObjectTypeName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClParenCadastralNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CadastralNumber', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=1024)),
                ('doc_number', models.CharField(max_length=64)),
                ('doc_date', models.DateField(default=datetime.date.today)),
                ('doc_author', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FilesCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('filepath', models.CharField(default=None, max_length=256)),
                ('urlfile', models.URLField(default=None, max_length=1024)),
                ('datetime_load', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XmlDocEgrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=256)),
                ('filepath', models.CharField(default=None, max_length=256)),
                ('urlfile', models.URLField(default=None, max_length=1024)),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.Docs')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_num', models.CharField(max_length=64)),
                ('cad_num_block', models.CharField(default=None, max_length=64)),
                ('obj_type', models.CharField(default='002001001000', max_length=64)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.CadastrCosts')),
                ('filecost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.FilesCost')),
            ],
        ),
        migrations.CreateModel(
            name='ClObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CadastralNumber', models.CharField(max_length=64)),
                ('DateCreated', models.DateField()),
                ('DateRemoved', models.DateField(blank=True, null=True)),
                ('DateCadastralRecord', models.DateField(blank=True, null=True)),
                ('CadastralBlock', models.CharField(max_length=64)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('AssignationConsName', models.CharField(blank=True, max_length=256, null=True)),
                ('Floors', models.CharField(blank=True, max_length=64, null=True)),
                ('UndergroundFloors', models.CharField(blank=True, max_length=64, null=True)),
                ('Area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Number_OnPlan', models.CharField(blank=True, max_length=256, null=True)),
                ('LevelNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('LevelType', models.CharField(blank=True, max_length=8, null=True)),
                ('DegreeReadiness', models.CharField(blank=True, max_length=8, null=True)),
                ('cadnumnum', models.ManyToManyField(blank=True, through='cost_cadastr.ClCadNumNum', to='cost_cadastr.ClObject')),
                ('classignationbuilding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClAssignationBuilding')),
                ('classignationcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClAssignationCode')),
                ('classignationtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClAssignationType')),
                ('clcadcost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClCadCost')),
                ('clementconstr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClElementConstr')),
                ('clexplorationchar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClExploitationChar')),
                ('clkeyparam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClKeyParam')),
                ('cllocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.ClLocation')),
                ('clobjecttype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClObjectType')),
                ('clparencadastralnumbers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClParenCadastralNumbers')),
            ],
        ),
        migrations.AddField(
            model_name='clkeyparam',
            name='valuetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClKeyParamTypes'),
        ),
        migrations.CreateModel(
            name='ClDataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_load', models.DateField(auto_now=True, null=True)),
                ('files_fir', models.URLField(default=None, max_length=1024)),
                ('files_fir_url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('clobject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.ClObject')),
            ],
        ),
        migrations.AddField(
            model_name='clcadnumnum',
            name='cad_num_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cad_num_child', to='cost_cadastr.ClObject'),
        ),
        migrations.AddField(
            model_name='clcadnumnum',
            name='cad_num_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cad_num_parent', to='cost_cadastr.ClObject'),
        ),
        migrations.AddField(
            model_name='cadastrcosts',
            name='doc_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.Docs'),
        ),
    ]
