# Generated by Django 2.2.12 on 2020-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescost',
            name='urlfile',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
