# Generated by Django 2.2.12 on 2020-09-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0002_auto_20200913_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clobject',
            old_name='clexplorationchar',
            new_name='clexploitationchar',
        ),
    ]
