# Generated by Django 2.2.12 on 2020-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0002_filescost_urlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescost',
            name='filepath',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='filescost',
            name='urlfile',
            field=models.URLField(default=None, max_length=1024),
        ),
    ]
