# Generated by Django 2.2.12 on 2020-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0003_auto_20200602_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='cad_num_block',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_type',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
