# Generated by Django 2.2.12 on 2020-09-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0003_auto_20200914_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clobject',
            name='clparencadastralnumbers',
        ),
        migrations.AddField(
            model_name='clparencadastralnumbers',
            name='clobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.ClObject'),
        ),
    ]
