# Generated by Django 2.2.12 on 2020-06-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0004_auto_20200602_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='obj_type',
            field=models.CharField(default='002001001000', max_length=64),
        ),
    ]
