# Generated by Django 2.2.12 on 2020-09-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0004_auto_20200914_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clparencadastralnumbers',
            name='clobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClObject'),
        ),
    ]
