# Generated by Django 2.2.12 on 2020-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0006_auto_20200915_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clobject',
            name='AssignationConsName',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
