# Generated by Django 2.2.12 on 2020-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0007_auto_20200915_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcadcost',
            name='unut',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clcadcost',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
