# Generated by Django 2.2.12 on 2020-09-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0009_auto_20200915_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clobject',
            name='LevelNumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clobject',
            name='LevelType',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
