# Generated by Django 2.2.12 on 2020-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0010_auto_20200920_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcadnumnum',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
