# Generated by Django 2.2.12 on 2020-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0012_auto_20200922_1618'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clobject',
            index=models.Index(fields=['CadastralNumber'], name='cost_cadast_Cadastr_a0cc6a_idx'),
        ),
    ]
