# Generated by Django 2.2.12 on 2020-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0013_auto_20200925_1613'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clcadnumnum',
            index=models.Index(fields=['cad_num_parent', 'cad_num_child'], name='cost_cadast_cad_num_8e4223_idx'),
        ),
        migrations.AddIndex(
            model_name='clkeyparam',
            index=models.Index(fields=['value', 'valuetype'], name='cost_cadast_value_2f0ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='clkeyparamtypes',
            index=models.Index(fields=['ClKeyParamCode', 'ClKeyParamName'], name='cost_cadast_ClKeyPa_265fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='clparencadastralnumbers',
            index=models.Index(fields=['CadastralNumber'], name='cost_cadast_Cadastr_bf9711_idx'),
        ),
    ]
