# Generated by Django 2.2.12 on 2020-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0014_auto_20200925_1621'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clobject',
            name='cost_cadast_Cadastr_a0cc6a_idx',
        ),
        migrations.AddIndex(
            model_name='clobject',
            index=models.Index(fields=['CadastralNumber', 'DateCreated', 'DateCadastralRecord'], name='cost_cadast_Cadastr_a6fa2d_idx'),
        ),
    ]
