# Generated by Django 2.2.12 on 2020-09-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0015_auto_20200926_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClListRatingReady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_list_name', models.URLField(default=None, max_length=1024)),
                ('file_list_url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('date_period_start', models.DateField()),
                ('date_period_end', models.DateField()),
                ('date_list_create', models.DateField()),
                ('total_objects_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='clobject',
            name='cllistratingready',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClListRatingReady'),
        ),
    ]
