# Generated by Django 2.2.12 on 2020-09-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0016_auto_20200926_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clobjecttype',
            name='ObjectTypeCode',
            field=models.CharField(max_length=12),
        ),
    ]
