# Generated by Django 2.2.12 on 2020-09-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0017_auto_20200929_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clcadcost',
            old_name='unut',
            new_name='unit',
        ),
    ]
