# Generated by Django 2.2.12 on 2020-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0018_auto_20200929_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cllocation',
            name='apart_number',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
