# Generated by Django 2.2.12 on 2020-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0019_auto_20200930_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cllocation',
            name='postal',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
