# Generated by Django 2.2.12 on 2020-09-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0020_cllocation_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcadnumnum',
            name='cad_num_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cad_num_child', to='cost_cadastr.ClObject'),
        ),
        migrations.AlterField(
            model_name='clcadnumnum',
            name='cad_num_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cad_num_parent', to='cost_cadastr.ClObject'),
        ),
    ]
