# Generated by Django 2.2.12 on 2020-09-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0021_auto_20200930_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_OnPlan', models.CharField(blank=True, max_length=256, null=True)),
                ('LevelNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('LevelType', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clobject',
            name='cllevels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.ClLevels'),
        ),
    ]
