# Generated by Django 2.2.12 on 2020-10-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0022_auto_20201001_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clobject',
            name='LevelNumber',
        ),
        migrations.RemoveField(
            model_name='clobject',
            name='LevelType',
        ),
        migrations.RemoveField(
            model_name='clobject',
            name='Number_OnPlan',
        ),
        migrations.RemoveField(
            model_name='clobject',
            name='cllevels',
        ),
        migrations.AddField(
            model_name='cllevels',
            name='clobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClObject'),
        ),
    ]
