# Generated by Django 2.2.12 on 2020-10-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0023_auto_20201001_1348'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classignationbuilding',
            index=models.Index(fields=['AssignationBuildingCode'], name='cost_cadast_Assigna_f89779_idx'),
        ),
        migrations.AddIndex(
            model_name='classignationcode',
            index=models.Index(fields=['AssignationFlatCode'], name='cost_cadast_Assigna_946cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='classignationtype',
            index=models.Index(fields=['AssignationTypeCode'], name='cost_cadast_Assigna_c0a368_idx'),
        ),
        migrations.AddIndex(
            model_name='cllevels',
            index=models.Index(fields=['LevelType', 'LevelNumber'], name='cost_cadast_LevelTy_0ecd86_idx'),
        ),
        migrations.AddIndex(
            model_name='clobjecttype',
            index=models.Index(fields=['ObjectTypeCode'], name='cost_cadast_ObjectT_ba8bd5_idx'),
        ),
    ]
