# Generated by Django 2.2.12 on 2020-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0024_auto_20201004_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cllistratingready',
            name='date_list_create',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cllistratingready',
            name='file_list_name',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
