# Generated by Django 2.2.12 on 2021-03-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0025_auto_20201006_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('filepath', models.CharField(default=None, max_length=256)),
                ('urlfile', models.URLField(default=None, max_length=1024)),
                ('datetime_load', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='docs',
            name='filedocs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_cadastr.FileDocs'),
        ),
    ]
