# Generated by Django 2.2.12 on 2021-03-29 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0026_auto_20210301_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClElementConstrObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clobject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClObject')),
                ('valuetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClElementConstr')),
            ],
        ),
    ]
