# Generated by Django 2.2.12 on 2021-03-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0027_clelementconstrobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clobject',
            name='clementconstr',
        ),
    ]
