# Generated by Django 2.2.12 on 2021-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0028_remove_clobject_clementconstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filescost',
            name='filename',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
