# Generated by Django 2.2.12 on 2021-04-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0030_auto_20210413_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClUtilizationsLandUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizationCode', models.CharField(max_length=12)),
                ('utilizationName', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddIndex(
            model_name='clutilizationslanduse',
            index=models.Index(fields=['utilizationCode'], name='cost_cadast_utiliza_d27c29_idx'),
        ),
        migrations.AddField(
            model_name='clutilizations',
            name='utilizationLandUseCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClUtilizationsLandUse'),
        ),
    ]
