# Generated by Django 2.2.12 on 2021-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0031_auto_20210420_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clobject',
            name='Area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
