# Generated by Django 2.2.12 on 2021-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0032_auto_20210420_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutilizations',
            name='utilizationByDoc',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
