# Generated by Django 2.2.12 on 2021-04-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_cadastr', '0033_auto_20210420_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clobject',
            name='cloldnumbers',
        ),
        migrations.AddField(
            model_name='cloldnumbers',
            name='clobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cost_cadastr.ClObject'),
        ),
        migrations.AlterField(
            model_name='cloldnumbers',
            name='oldNumber',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
